sudo: required
dist: trusty
os: windows
language: java
jdk:
  - oraclejdk8
addons:
  sauce_connect: true
before_script:
  - curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash
script: mvn -Dsurefire.suiteXmlFiles=/src/test/resources/testng.xml clean test

