language: java
jdk: openjdk8
before_install:
  - export | grep SAUCE_
script: mvn -Dsurefire.suiteXmlFiles=/src/test/resources/testng.xml clean test
addons:
  sauce_connect:
    username: $SAUCELABS_USERNAME
    access_key: $SAUCELABS_ACCESS_KEY



