dist: xenial
services:
  - xvfb
addons:
  chrome: stable

language: java
jdk: openjdk8
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - xvfb-run --server-args="-screen 0 1024x768x24" make test
  - sleep 3

script: mvn clean test






