language: java
jdk: openjdk8
services:
  - docker
addons:
  sauce_connect:
    username: $SAUCELABS_USERNAME
    access_key: $SAUCELABS_ACCESSKEY
install: true
#script: mvn -Dsurefire.suiteXmlFiles=/src/test/resources/testng.xml clean test

script: travis_wait 60 ./travis_script.sh

